### PR TITLE
Add better support for plugins

### PR DESCRIPTION
**Pull request by bethac07**
Allow users to grab a specific plugins repo commit, as well as to install

### CODE REVIEW

**Comment by bethac07** [comment]
Still todo - logic for checking commit hash and requirements file are non-empty/good. (Maybe need to git pull in commit side also?)

**Comment by bethac07** [comment]
We had a discussion and decided that we actually don't want to avoid failures when we are trying to checkout or install plugins things - because it might lead a user to think they're running a newer version when in fact it's an older version. So we'll try to add a nice error message but otherwise let it crash.

**Comment by ErinWeisbart** [comment]
LGTM. I added a commit to make configs backward compatible. That okay with you? (and then I ran black to make sure I hadn't introduced a mistake and it decided to make everything look different, but hey no mistakes...)

**Comment by bethac07** [comment]
> I added a commit to make configs backward compatible. That okay with you?
I think the odds that someone would have an updated run.py but NOT an updated config.py would be very low, since both changes were introduced in the same commit (you'd have to be manually updating your run.py), but no harm in being defensive. But as an FYI that's why I didn't originally do so, unlike in other cases where we've introduced new environment variables into the containers, since containers and run.py are more likely to be out of sync, it's more important to be defensive there.

> and then I ran black to make sure I hadn't introduced a mistake and it decided to make everything look different, but hey no mistakes...
Ok! Let's just then NOT squash commits when merging this PR, which I usually do, but I don't want to confuse the two reasons for changes.

**Comment by ErinWeisbart** [comment]
> I think the odds that someone would have an updated run.py but NOT an updated config.py would be very low, since both changes were introduced in the same commit (you'd have to be manually updating your run.py), but no harm in being defensive. 

Makes logical sense, I was just picturing someone copying a config from project to project instead of editing the fresh config. If you think that's not something we don't need to protect against, you're welcome to revert my commits.

**Comment by ErinWeisbart** [comment]
One further thought - do we want to edit tag in Makefile to match? 
`tag = 2.0.0_4.2.3`
Would close #125

**Pull request merged**
